import { afinn165 } from 'afinn-165';

// Generated by CoffeeScript 1.9.3

/*
sentimood v1.0
a CoffeeScript browser-compatible port of thinkroth's Sentimental
open-source under the MIT license, (c) Ethan Arterberry 2015
 */
function Sentimood() {
  this.negativity = function (phrase) {
    var addPush, hits, i, item, j, len, noPunctuation, tokens, words;
    addPush = function (t, score) {
      hits -= score;
      return words.push(t);
    };
    noPunctuation = phrase.replace(/[^a-zA-Z ]+/g, ' ').replace('/ {2,}/', ' ');
    tokens = noPunctuation.toLowerCase().split(' ');
    hits = 0;
    words = [];
    for (i = j = 0, len = tokens.length; j < len; i = ++j) {
      item = tokens[i];
      if (afinn165.hasOwnProperty(item)) {
        if (afinn165[item] < 0) {
          addPush(item, afinn165[item]);
        }
      }
    }
    return {
      score: hits,
      comparative: hits / words.length,
      words: words,
    };
  };

  this.positivity = function (phrase) {
    var addPush, hits, i, item, j, len, noPunctuation, tokens, words;
    addPush = function (t, score) {
      hits += score;
      return words.push(t);
    };
    noPunctuation = phrase.replace(/[^a-zA-Z ]+/g, ' ').replace('/ {2,}/', ' ');
    tokens = noPunctuation.toLowerCase().split(' ');
    hits = 0;
    words = [];
    for (i = j = 0, len = tokens.length; j < len; i = ++j) {
      item = tokens[i];
      if (afinn165.hasOwnProperty(item)) {
        if (afinn165[item] > 0) {
          addPush(item, afinn165[item]);
        }
      }
    }
    return {
      score: hits,
      comparative: hits / words.length,
      words: words,
    };
  };

  this.analyze = function (phrase) {
    var neg, pos;
    pos = this.positivity(phrase);
    neg = this.negativity(phrase);
    return {
      score: pos.score - neg.score,
      comparative: pos.comparative - neg.comparative,
      positive: pos,
      negative: neg,
    };
  };
}

export default Sentimood;
